### ISSUE TITLE
Ensure that you're closing SQL connections when logical.

### ISSUE THREAD

**Issue by Leopere** [King-Fisher/ServerMonitor#7]
I've had servers in the past that had plugins that didn't terminate connections well and we would end up having to tweak many settings in the SQL server to accommodate.  Also I don't know if its possible but to optimize the database on occasion would also be smart.

Anyways sorry for communicating via this.  I just wanted to file whatever came to mind so you have ideas for stuff to add if you want.

**Comment by King-Fisher** [comment]
Fixed.
